export const ARTIFACT_TYPES = [
  "filing",
  "evidence_catalog",
  "evidence_identity",
  "themes",
  "topic_registry",
  "topic_assignment",
  "topic_evolution",
  "quarter_change",
  "financial_statements",
  "structured_intelligence",
  "company_knowledge_candidate",
  "governance_decision",
  "company_knowledge",
  "business_signals",
  "commitment_tracking",
  "narrative_consistency",
  "accounting_stability",
  "capital_allocation_tracking",
  "trust_signals",
  "quarter_understanding",
  "investor_intelligence",
  "partner_domain",
  "prompt_registry",
  "concept_registry",
  "evaluation_report",
  "dependency_index",
] as const;

export type ArtifactType = typeof ARTIFACT_TYPES[number];
